name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/local-dev-runner.mjs predev"
dev = "node scripts/local-dev-runner.mjs dev"
